<!DOCTYPE html>
<html lang="es">

<head>
    <title>Payroll | <?php if(isset($this->title_)) {echo $this->title_;} ?></title>
    
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="shortcut icon" href="./public/img/stormfellicon.png"/>
    <link rel="stylesheet" href="/public/font/iconsmind-s/css/iconsminds.css" />
    <link rel="stylesheet" href="/public/font/simple-line-icons/css/simple-line-icons.css" />
    
    <link rel="stylesheet" href="/public/css/vendor/bootstrap.min.css" />
    <link rel="stylesheet" href="/public/css/vendor/bootstrap.rtl.only.min.css" />
    <link rel="stylesheet" href="/public/css/vendor/bootstrap-float-label.min.css" />
    <link rel="stylesheet" href="/public/css/main.css" />
</head>

<body class="background show-spinner no-footer">
    <div class="fixed-background"></div>
    <main>
        <div class="container">
            <div class="row h-100">
                <div class="col-12 col-md-10 mx-auto my-auto">
                    <div class="card auth-card">
                        <div class="position-relative image-side ">
                            <p class=" text-white h2">MAGIC IS IN THE DETAILS</p>
                            <p class="white mb-0">
                            Please enter your login credentials
                            </p>
                        </div>
                        <div class="form-side">
                            <span class="logo-single" style="background-size: cover;"></span>
                            <h6 class="mb-4">Log in</h6>
                            <form id="login-form">
                                <label class="form-group has-float-label mb-4">
                                    <input class="form-control" name="email" type="email" required/>
                                    <span>E-mail</span>
                                </label>

                                <label class="form-group has-float-label mb-4">
                                    <input class="form-control" type="password" name="password" required/>
                                    <span>Password</span>
                                </label>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="index/ResetPassword">Did you forget your password?</a>
                                    <button class="btn btn-primary btn-lg btn-multiple-state btn-shadow" type="submit">START</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <div class="modal fade" id="change-password-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="change-password-form">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Por favor ingresa tu nueva contraseña</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    
                        <p>Es necesario que cambies tu contraseña para ingresar</p>
                        
                        <label class="w-100 mt-2">
                            Nueva contraseña
                            <input type="password" class="form-control" name="password" required placeholder="Ingresa tu nueva contraseña">
                        </label>
                        
                        <label class="w-100 mt-3">
                            Confirmar contraseña
                            <input type="password" class="form-control" name="confirmpassword" required placeholder="Confirma tu nueva contraseña">
                        </label>
                        
                        <input type="hidden" name="email"/>
                    
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <script src="/public/js/vendor/jquery-3.3.1.min.js"></script>
    <script src="/public/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="/public/js/vendor/jquery.validate/jquery.validate.min.js"></script>
    <script src="/public/js/vendor/bootstrap-notify.min.js"></script>
    <script src="/public/js/dore.script.js"></script>
    <script src="/public/js/scripts.js"></script>

    <script src="/public/js/api/Consts.js"></script>
    <script src="/public/js/api/Utils.js"></script>
    <script src="/public/js/api/AlertPop.js"></script>
    <script src="/public/js/api/FormValidator.js"></script>
    <script src="/public/js/api/WebClient.js"></script>
    <script src="/views/user/js/login.js"></script>
</body>

</html>