<!DOCTYPE html>
<html lang="es">

<head>
    <title>Teella | <?php if(isset($this->title_)) {echo $this->title_;} ?></title>
    
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="shortcut icon" href="/public/img/favicon.png">
    <link rel="stylesheet" href="/public/font/iconsmind-s/css/iconsminds.css" />
    <link rel="stylesheet" href="/public/font/simple-line-icons/css/simple-line-icons.css" />
    
    <link rel="stylesheet" href="/public/css/vendor/bootstrap.min.css" />
    <link rel="stylesheet" href="/public/css/vendor/bootstrap.rtl.only.min.css" />
    <link rel="stylesheet" href="/public/css/vendor/bootstrap-float-label.min.css" />
    <link rel="stylesheet" href="/public/css/main.css" />
</head>

<body class="background show-spinner no-footer">
    <div class="fixed-background"></div>
    <main>
        <div class="container">
            <div class="row h-100">
                <div class="col-12 col-md-10 mx-auto my-auto">
                    <div class="card auth-card">
                        <div class="position-relative image-side ">
                            <p class=" text-white h2">MAGIC IS IN THE DETAILS</p>
                            <p class="white mb-0">
                                Por favor ingresa tu e-mail para recuperar tu contraseña.
                            </p>
                        </div>
                        <div class="form-side">
                            <a href="/">
                                <span class="logo-single" style="background-size: cover;"></span>
                            </a>
                            <h6 class="mb-4">Recuperar Contraseña</h6>
                            <form id="forgot-password-form">
                                <label class="form-group has-float-label mb-4">
                                    <input class="form-control" type="email" name="email" required/>
                                    <span>E-mail</span>
                                </label>

                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="javascript:history.back()">Volver</a>
                                    <button class="btn btn-primary btn-lg btn-shadow" type="submit">ENVIAR</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="/public/js/vendor/jquery-3.3.1.min.js"></script>
    <script src="/public/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="/public/js/vendor/jquery.validate/jquery.validate.min.js"></script>
    <script src="/public/js/vendor/bootstrap-notify.min.js"></script>
    <script src="/public/js/dore.script.js"></script>
    <script src="/public/js/scripts.js"></script>

    <script src="/public/js/api/Consts.js"></script>
    <script src="/public/js/api/Utils.js"></script>
    <script src="/public/js/api/AlertPop.js"></script>
    <script src="/public/js/api/FormValidator.js"></script>
    <script src="/public/js/api/WebClient.js"></script>
    <script src="/views/user/js/resetpassword.js"></script>
</body>

</html>