<input type="hidden" value="<?php echo $_SESSION['RoleId'] ?>" class="RoleId">


<main class="default-transition">

    <div class="container-fluid disable-text-selection">

        <div class="row">
            <div class="col-xs-9 col-md-10">
                <h1>Master Payment </h1>




                <div class="mb-2">
                    <div class="top-right-button-container">
                        <div class="btn-group">
                            <button class="btn btn-secondary btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                EXPORT
                            </button>
                            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 43px, 0px);">
                                <a class="dropdown-item" id="dataTablesCopy" href="#">Copy</a>
                                <a class="dropdown-item" id="dataTablesExcel" href="#">Excel</a>
                                <a class="dropdown-item" id="dataTablesCsv" href="#">Csv</a>
                                <a class="dropdown-item" id="dataTablesPdf" href="#">Pdf</a>
                            </div>
                        </div>
                    </div>
                    <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions" role="button" aria-expanded="true" aria-controls="displayOptions">
                        Display Options
                        <i class="simple-icon-arrow-down align-middle"></i>
                    </a>
                    <div class="collapse dont-collapse-sm" id="displayOptions">
                        <div class="d-block d-md-inline-block">
                            <div class="search-sm d-inline-block float-md-left mr-1 mb-1 align-top">
                                <input class="form-control" placeholder="Search Master Payment" type="search" id="searchUserInput">
                            </div>
                        </div>
                        <div class="float-md-right dropdown-as-select" id="pageLengthPlansTable">
                            <span class="text-muted text-small">Quantity of items per page: </span>
                            <button class="btn btn-outline-dark btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                10
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">5</a>
                                <a class="dropdown-item active" href="#">10</a>
                                <a class="dropdown-item" href="#">20</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-3 col-md-2 d-flex justify-content-end" style="align-items: center;">
                <div class="shadow-sm border p-2 rounded-lg text-center mr-0" style="width: max-content;">
                    <a href="" class="create-user-link">
                        <h2 class="m-0 p-0 w-100"><i class="iconsminds-money-bag"></i></h2>

                        create Master Payment
                    </a>
                </div>
            </div>
        </div>

        <div class="separator mb-5"></div>
        <div id="users-list-container">
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover" id="exportTable">


                        <thead>
                            <tr>
                                <th scope="col">Reference</th>
                                <th scope="col">Company</th>
                                <th scope="col">Ammount</th>
                                <th scope="col">Total</th>
                                <th scope="col">Date</th>

                            </tr>
                        </thead>
                        <tbody class="list">


                        </tbody>
                    </table>
                </div>
            </div>
            <!--   <div class="card">
                <div class="card-body">
                    <div class="jumbotron">
                        <h1 class="display-4">No records found
                        </h1>

                        <div>
                            <p class="lead float-left mt-3">You can start creating User by clicking on the icon
                            </p>
                            <a href="" class="text-center float-right float-lg-left ml-4 p-2 shadow-sm border 
                                rounded-lg create-user-link">
                                <h2 class="m-0 p-0 w-100"><i class="iconsminds-money-bag"></i></h2>

                                create Master Payment
                            </a>
                        </div>

                    </div>
                </div>
            </div>-->

        </div>

    </div>

</main>


<div class="modal fade" id="create-user-modal">
    <div class="mb-2">


        <div class="modal-dialog modal-lg" role="document">




            <div class="modal-content">
                <form id="create-user-form" novalidate="novalidate">
                    <div class="modal-header">
                        <h5 class="modal-title" id="create-user-modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">

                        <h2>user information
                        </h2>
                        <div class="separator mb-2"></div>

                        <div class="row">
                            <input type="text" class="form-control" name="idCompanyPayment" required placeholder="idCompanyPayment" style="display: none;" />
                            <div class="col-md-6">
                            </div>


                        </div>
                        <input type="text" class="form-control" name="idSystemUser" required placeholder="Ingresar apellido" style="display: none;" />

                        <div class="row">

                            <div class="col">

                                <label class="mb-3 w-100 has-float-label">
                                    <select class="form-control select2-single" name="Company_idCompany" id="Company_idCompany" data-width="100%">

                                    </select>
                                    <span>Company_idCompany</span>
                                </label>


                                <label class="mb-3 w-100 has-float-label">
                                    <input type="text" class="form-control" name="CompanyPaymentReference" required placeholder="CompanyPaymentReference" />
                                    <span>CompanyPaymentReference</span>
                                </label>



                                <label class="mb-3 w-100 has-float-label">
                                    <input type="number" class="form-control" name="CompanyPaymentAmmount" placeholder="CompanyPaymentAmmount " />
                                    <span>Company Payment mmount</span>
                                </label>
                            </div>

                        </div>



                        <div class="col" style="text-align:right; width:100%; padding:15;">

                            <button type="submit" class="btn btn-info default mb-1" id="create-user-modal-button" style="text-align:right">Guardar</button>
                        </div>
                    </div>
            </div>

            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>

<link rel="stylesheet" type="text/css" href="/Content/font-awesome/css/font-awesome.min.css" />



<!-- you need to include the shieldui css and js assets in order for the components to work -->
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/jszip.min.js"></script>

<script type="text/javascript">
    jQuery(function($) {
        $("#dataTablesPdf").click(function() {
            // parse the HTML table element having an id=exportTable
            var dataSource = shield.DataSource.create({
                data: "#exportTable",
                schema: {
                    type: "table",
                    fields: {
                        Reference: {
                            type: String
                        },
                        Company: {
                            type: String
                        },
                       Ammount: {
                            type: String
                        },
                      Total: {
                            type: String
                        },
                     Date: {
                            type: String
                        }

                    }
                }
            });

            // when parsing is done, export the data to PDF
            dataSource.read().then(function(data) {
                var pdf = new shield.exp.PDFDocument({
                    author: "Pay Roll",
                    created: new Date()
                });

                pdf.addPage("a4", "portrait");

                pdf.table(
                    50,
                    50,
                    data,
                    [{
                            field: "Reference",
                            title: "Reference",
                            width: 80
                        },
                        {
                            field: "Company",
                            title: "Company",
                            width: 80
                        },
                        {
                            field: "Ammount",
                            title: "Payment Ammount",
                            width: 80
                        },
                        {
                            field: "Total",
                            title: "Payment Total",
                            width: 80
                        },
                        {
                            field: "Date",
                            title: "Payment Date",
                            width: 160
                        },


                    ], {
                        margins: {
                            top: 50,
                            left: 50
                        }
                    }
                );
                var year = (new Date());
                console.log(year);
                pdf.saveAs({
                

                    fileName: year+"payment"
                });
            });
        });
    });
</script>

<style>
    #exportButton {
        border-radius: 0;
    }
</style>