<main class="default-transition">



    <div class="container-fluid disable-text-selection">
<!--
        <ul class="nav nav-tabs separator-tabs ml-0 mb-5" id="myTab" role="tablist">
            <li class="nav-item" style="width: 50%;">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Company</a>
            </li>
            
            <li class="nav-item" style="width: 50%;">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Company Types</a>
            </li>
            -->
        </ul>


        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                <div class="row">
                    <div class="col-xs-9 col-md-10">
                        <h1>Company</h1>


                        <div class="mb-2">
                            <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions" role="button" aria-expanded="true" aria-controls="displayOptions">
                                Display Options
                                <i class="simple-icon-arrow-down align-middle"></i>
                            </a>
                            <div class="collapse dont-collapse-sm" id="displayOptions">
                                <div class="d-block d-md-inline-block">
                                    <div class="search-sm d-inline-block float-md-left mr-1 mb-1 align-top">
                                        <input class="form-control" placeholder="Search Company" id="searchCompanyInput">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-3 col-md-2 d-flex justify-content-end" style="align-items: center;">
                        <div class="shadow-sm border p-2 rounded-lg text-center mr-0" style="width: max-content;">
                            <a href="" class="create-company-link">
                                <h2 class="m-0 p-0 w-100"><i class="iconsminds-building"></i></h2>
                                Create Company
                            </a>
                        </div>
                    </div>
                </div>

                <div class="separator mb-5"></div>
                <div id="companies-list-container">

                    <div class="card">
                        <div class="card-body">
                            <div class="jumbotron">
                                <h1 class="display-4">No companies have been created</h1>

                                <div>
                                    <p class="lead float-left mt-3">Click on "Create Company" to add a new company </p>
                                    <a href="" class="text-center float-right float-lg-left ml-4 p-2 shadow-sm border 
                                rounded-lg create-company-link">
                                        <h2 class="m-0 p-0 w-100"><i class="iconsminds-add-user"></i></h2>
                                        Create Company
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="tab-pane fade show " id="contact" role="tabpanel" aria-labelledby="contact-tab">

                <div class="row">
                    <div class="col-xs-9 col-md-10">
                        <h1>Company type</h1>


                        <div class="mb-2">
                            <a class="btn pt-0 pl-0 d-inline-block d-md-none" data-toggle="collapse" href="#displayOptions" role="button" aria-expanded="true" aria-controls="displayOptions">
                                Display Options
                                <i class="simple-icon-arrow-down align-middle"></i>
                            </a>
                            <div class="collapse dont-collapse-sm" id="displayOptions">
                                <div class="d-block d-md-inline-block">
                                    <div class="search-sm d-inline-block float-md-left mr-1 mb-1 align-top">
                                        <input class="form-control" placeholder="Search company type" id="searchCompanyInput">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-xs-3 col-md-2 d-flex justify-content-end" style="align-items: center;">
                        <div class="shadow-sm border p-2 rounded-lg text-center mr-0" style="width: max-content;">
                            <a href="" class="create-company-link">
                                <h2 class="m-0 p-0 w-100"><i class="iconsminds-building"></i></h2>
                                Create Company Type
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    </div>


</main>



<div class="modal fade" id="create-company-modal" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="create-company-form" novalidate="novalidate">
                <div class="modal-header">
                    <h5 class="modal-title" id="create-company-modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <h2>Company information
                    </h2>
                    <div class="separator mb-2"></div>

                    <div class="row">

                        <div class="col-md-6">

                            <div class="mx-auto mb-3" style="height: 150px; width: 150px;">
                                <div class="card h-100 overflow-hidden">
                                    <div class="position-relative h-100">
                                        <img class="card-img-top" id="create-company-img" src="/public/img/user_placeholder.png" alt="company Img">
                                        <label class="badge badge-pill badge-theme-1 position-absolute badge-top-left" title="Cargar Imagen" for="create-company-img-file">
                                            Upload Image </label>
                                            <input type="file" class="sr-only" id="create-company-img-file" accept="image/x-png,image/gif,image/jpeg,image/png" >

                                    </div>
                                </div>
                            </div>


                        </div>

                        <div class="col-md-6">

                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="CompanyName" id="CompanyName" required placeholder="Company Name" />
                                <span>Company Name</span>
                            </label>
                            <label class="mb-3 w-100 has-float-label">
                                <input type="number" class="form-control" name="ContactPhone" required placeholder="Company Phone" />
                                <span>Contact Phone</span>
                            </label>
                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="ContactName" required placeholder="Contact Name" />
                                <span>Contact Name</span>
                            </label>

                        </div>

                    </div>

                    <h2 class="mt-2">Financial Information
                    </h2>
                    <div class="separator mb-2"></div>
                    <div class="row">



                        <input type="text" class="form-control" name="idCompany" id="idCompany" required placeholder="Ingresar apellido" style="display: none;" />


                        <div class="col">


                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="companyCurrentMoney" id="companyCurrentMoney" disabled />
                                <span>Money Available</span>
                            </label>

                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="companyDebt" id="companyDebt" disabled placeholder="Company Name" />
                                <span>Company Debt</span>
                            </label>


                            <label class="mb-3 w-100 has-float-label">


                                <select class="form-control select2-single" name="CompanyHaveLoan" id="CompanyHaveLoan" data-width="100%">
                                    <option value="0">NO</option>
                                    <option value="1">YES</option>

                                </select>
                                <span>Company Have Loan</span>


                            </label>

                            <label class="mb-3 w-100 has-float-label"> 
                                <input type="text" class="form-control money" name="CompanyLoanMaxAmmount" id="CompanyLoanMaxAmmount" placeholder="" />
                                <span>Company Loan Max Ammount</span>
                            </label>

                            <label class="mb-3 w-100 has-float-label">
                                <input type="number" class="form-control" name="Fee" id="Fee" placeholder="" />
                                <span>Fee (Percentage)</span>
                            </label>


 
                            <label class="mb-3 w-100 has-float-label">
                                <select class="form-control select2-single" name="PayablePaysFee" id="PayablePaysFee" data-width="100%">
                                <option  selected > -- select an option -- </option>
                                    <option value="0">Company</option>
                                    <option value="1">Payable</option>
                                </select>

                                <span>Service Charge Paid by</span> 
                            </label>

                            <label class="mb-3 w-100 has-float-label">
                                <select class="form-control select2-single" name="PaymentPeriod" id="PaymentPeriod" data-width="100%">
                                    <option value=""></option>
                                    <option  selected > -- select an option -- </option>

                                    <option value="biweekly">biweekly</option>
                                    <option value="monthly">monthly</option>
                                </select>

                                <span>Payment Period</span>
                            </label>

                            <label class="mb-3 w-100 has-float-label">

                                <select class="form-control select2-single" name="CompanyTypeId" id="CompanyTypeId" data-width="100%">

                                </select>
                                <span>Company Type</span>


                            </label>


                            <label class="mb-3 w-100 has-float-label">

                                <select class="form-control select2-single" name="companyStatus_id" id="companyStatus_id" data-width="100%">

                                </select>
                                <span>Status</span>


                            </label>


                        </div>


                    </div>


                    <h2 class="mt-2">Company Locations
                    </h2>
                    <div class="separator mb-2"></div>
                    <div class="row">
                        <div class="col">


                            <button type=button class="btn btn-success mb-1 create-location-company-link" id="open-create-location" style="text-align:center">Create Location</button>


                        </div>



                    </div>
                    <div class="row">
                        <div class="col">


                            <table class="table table-hover">

                                <thead>
                                    <tr>
                                        <th scope="col">Location Description</th>
                                        <th scope="col">Location Address</th>

                                        <th scope="col">Location Status</th>
                                        <th scope="col">Edit</th>

                                    </tr>
                                </thead>
                                <tbody class="list">
                                    <tr>

                                    </tr>

                                </tbody>
                            </table>

                        </div>
                    </div>






                    <div class="separator mb-2"></div>



                    <div class="row">


                        <div class="col" style="text-align:right; width:100%; padding:15;">

                            <button type="submit" class="btn btn-info default mb-1" id="create-company-modal-button" style="text-align:right">Crear</button>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>



<div class="modal fade modal-left" id="create-location-company-modal" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="dialog">
        <div class="modal-content">
            <form id="create-location-company-form" novalidate="novalidate">
                <div class="modal-header">
                    <h5 class="modal-title" id="create-location-company-modal-title">Create location</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col">


                            <input type="text" class="form-control" name="idCompanyLocation" id="idCompanyLocation" required placeholder="Ingresar apellido" style="display: none;" />


                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="CompanyLocationAddress" id="CompanyLocationAddress" placeholder="Company Location Address" />
                                <span>Company Location Address </span>
                            </label>

                            <label class="mb-3 w-100 has-float-label">
                                <input type="text" class="form-control" name="CompanyLocationDescription" id="CompanyLocationDescription" placeholder="Company Location Description" />
                                <span>Company Location Description
                                </span>
                            </label>

                            <label class="mb-3 w-100 has-float-label">

                                <select class="form-control select2-single" name="CompanyLocationStatusId" id="CompanyLocationStatusId" data-width="100%">

                                </select>
                                <span>Company Location Status</span>


                            </label>
                            <button type=button class="btn btn-danger" id="create-location-company-modal-button" style="text-align:right">Create Location</button>

                        </div>

                    </div>
                </div>
        </div>
    </div>
</div>